package com.ninety5.habitate.data.repository

import com.ninety5.habitate.core.result.AppError
import com.ninety5.habitate.core.result.AppResult
import com.ninety5.habitate.data.local.dao.InsightDao
import com.ninety5.habitate.domain.mapper.toDomain
import com.ninety5.habitate.domain.mapper.toEntity
import com.ninety5.habitate.domain.model.Insight
import com.ninety5.habitate.domain.repository.InsightRepository
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.firstOrNull
import kotlinx.coroutines.flow.map
import timber.log.Timber
import javax.inject.Inject
import javax.inject.Singleton
import kotlin.coroutines.cancellation.CancellationException

@Singleton
class InsightRepositoryImpl @Inject constructor(
    private val insightDao: InsightDao
) : InsightRepository {

    override fun observeActiveInsights(): Flow<List<Insight>> {
        return insightDao.getActiveInsights().map { entities ->
            entities.map { it.toDomain() }
        }
    }

    override suspend fun generateInsights(): AppResult<List<Insight>> {
        // Insights are generated by InsightGenerator and stored locally
        return try {
            val insights = insightDao.getActiveInsights()
                .firstOrNull() ?: emptyList()
            AppResult.Success(insights.map { it.toDomain() })
        } catch (e: CancellationException) {
            throw e
        } catch (e: Exception) {
            Timber.e(e, "Failed to generate insights")
            AppResult.Error(AppError.from(e))
        }
    }

    override suspend fun dismissInsight(insightId: String): AppResult<Unit> {
        return try {
            insightDao.dismiss(insightId)
            AppResult.Success(Unit)
        } catch (e: CancellationException) {
            throw e
        } catch (e: Exception) {
            Timber.e(e, "Failed to dismiss insight: $insightId")
            AppResult.Error(AppError.from(e))
        }
    }

    override suspend fun refreshInsights(): AppResult<Unit> {
        // Local-only for now; InsightGenerator handles creation
        return AppResult.Success(Unit)
    }

    // ── Used by InsightGenerator ────────────────────────────────────────

    suspend fun addInsight(insight: com.ninety5.habitate.data.local.entity.InsightEntity) {
        insightDao.insert(insight)
    }
}
