package com.ninety5.habitate.domain.model

import java.time.Instant

/**
 * Domain model for an insight generated by the AI engine.
 */
data class Insight(
    val id: String,
    val type: InsightType,
    val title: String,
    val description: String,
    val priority: InsightPriority,
    val actionLabel: String?,
    val actionRoute: String?,
    val isDismissed: Boolean,
    val createdAt: Instant
)

enum class InsightType {
    STREAK_RISK, MILESTONE, INACTIVITY_ALERT,
    WEEKLY_SUMMARY, HABIT_SUGGESTION, PRODUCTIVITY_TIP,
    PATTERN_DETECTED, MOOD_CORRELATION, ENERGY_TREND,
    TASK_FAILURE, HABIT_FRICTION
}

enum class InsightPriority {
    LOW, MEDIUM, HIGH, CRITICAL
}
